spring.application.name=SpringAiDemo
#spring.ai.openai.api-key=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

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.image.options.model=dall-e-3

#second
spring.ai.openai.api-key=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
#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